package com.stomp.chat.model;

public enum SnapshotUpdateType {

  INITIAL_SNAPSHOT, DEALING_INITIAL_CARDS, DEALING_CARDS, REARRANGING_HAND, REARRANGING_TABLE_PLACE,
  DRAWING_WILDE_PARTY, DESTROY, STEAL, ENCHANT_WITH_BFF, ENCHANT, SWAP, ADD_DRAGGED, PROTECT_SELF;

}
